restart-times: 3
jobscript: sge-jobscript.sh
cluster: "sge-submit.py"
cluster-status: "sge-status.py"
cluster-cancel: "sge-cancel.py"
cluster-cancel-nargs: 20
max-jobs-per-second: 1
max-status-checks-per-second: 1
latency-wait: 60
local-cores: 1