__resources__:
  gpu: 
    - "gpu"
    - "nvidia_gpu"

__options__:
  jc:
    - "jc"
    - "jclass"
    - "job_class"

__default__:
  join: yes
  output: logs/sge/snakejob.{rulename}.{jobid}.log
  error: logs/sge/snakejob.{rulename}.{jobid}.log
